version: '3.3'
services:

  ## i2b2transmart stack ##
  # transmart
  transmart:
#    image: dbmi/i2b2transmart:18.1-Quickstart
    build:
        context: ./transmart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - solr
      - rserve
      - db
    volumes:
      - rserve-jobs:/tmp:rw
    networks:
      - public
    expose:
      - 8080

  # i2b2transmart database
  db:
    image: dbmi/i2b2transmart-db:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - public
    expose:
      - 1521
    # i2b2transmart database exposed port
    ports:
      - ${DOCKER_DB_PORT:-1521}:1521

  # Rserve
  rserve:
    image: dbmi/rserve:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    expose:
      - 6311
    volumes:
      - rserve-jobs:/tmp:rw
    networks:
      - public

  solr:
    image: dbmi/solr:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - public
    expose:
      - 8983

  ## Fractalis Stack ##
  fractalis:
    image: dbmi/fractalis:1.3.1-quickstart-hotfix
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    environment:
      - FRACTALIS_CONFIG=/config.py
    command: gunicorn -w 3 -b :5000 --timeout 90 --log-file - fractalis:app
    networks:
      - public
    expose:
      - 5000
    restart: always
    depends_on:
      - irct
      - redis
      - rabbitmq
      - worker

  worker:
    image: dbmi/fractalis:1.3.1-quickstart-hotfix
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    environment:
      - FRACTALIS_CONFIG=/config.py
    command: celery worker -A fractalis:celery -l debug --autoscale 16,4
    networks:
      - public
    restart: always
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    command: >
      sh -c "redis-server
      && redis-cli CONFIG SET maxmemory 4gb
      && redis-cli CONFIG SET maxmemory-policy allkeys-lru
      && redis-cli CONFIG SET save ''
      && redis-cli CONFIG SET appendonly no"
    networks:
      - public

  rabbitmq:
    image: rabbitmq:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - public

  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - irctdb
      - i2b2-wildfly
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - public
    expose:
      - 8080

  # PIC-SURE i2b2-wildfly resource
  i2b2-wildfly:
#    image: dbmi/i2b2-wildfly:18.1-Quickstart
    build:
        context: ./i2b2-wildfly
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    environment:
      - JAVA_OPTS=-Xms512m -Xmx4096m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    networks:
      - public
    expose:
      - 9090

  # IRCT DB
  irctdb:
    image: dbmi/irct-db:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    command: --datadir=/mysql/data
    networks:
      - public
    expose:
      - 3306
    # PIC-SURE database exposed port
    ports:
      - ${DOCKER_IRCT_DB_PORT:-3306}:3306
    volumes:
      - irct-data:/mysql/data

  nhaneshpds:
    image: dbmi/pic-sure-hpds-nhanes:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - hpdsui
    networks:
      - public
    expose:
      - 8080

  hpdsui:
#    image: dbmi/pic-sure-hpds-ui:18.1-Quickstart-v2
    build:
      context: ./hpdsui
    restart: always
    user: root
    env_file:
      - ${ENV_FILE}
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - public
#    volumes:
#      - /home/centos/tsmart-overrides.js:/usr/local/apache2/htdocs/tsmart-overrides.js:rw
#      - /home/centos/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:rw
volumes:
  # PIC-SURE database
  irct-data:
  # shared volume for R jobs
  rserve-jobs:

networks:
  public:
